### ISSUE TITLE
Issue with github-readme-stats

### ISSUE THREAD

**Issue by jslfree080** [kojix2/kojix2#5]
Hi!

I appreciate your beautiful projects you've been working with, but currently there seems to be an issue with github-readme-stats.

So I suggest you replace 'github-readme-stats.vercel.app' with 'github-readme-stats-git-masterrstaa-rickstaa.vercel.app'.
https://github.com/anuraghazra/github-readme-stats/issues/2380

Thank you.

**Comment by kojix2** [comment]
Thanks.
I fixed it by Deploying GitHub Readme Stats myself.

https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance

I didn't expect anyone to comment on my page. If it weren't for your comment, I would have left it unfixed for about a week, hoping it would get fixed eventually.

Best Regards & best wishes to you.
